dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "6.12.2"
before_install:
  - npm i -g npm@3.10.10
# workaround for https://github.com/travis-ci/travis-ci/issues/9024
sudo: required
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
# end workaround
